
CREATE PROCEDURE [dbo].[TrendQuarters]

@QuarterID INT =10
AS
BEGIN
DECLARE
@QUARTER NVARCHAR(5),
@YEAR INT,
@QUARTERNUMBER INT,
@LOADINGQUARTER VARCHAR(20)
SELECT @QUARTER=(SELECT Quarter FROM Quarter WHERE ID=@QuarterID)
SELECT @YEAR=(SELECT YEAR FROM Quarter WHERE ID=@QuarterID)
SELECT @LOADINGQUARTER=@QUARTER--+' '+CAST(@YEAR AS VARCHAR)



IF @QUARTER='Q1'
BEGIN
SELECT @LOADINGQUARTER+' VS'+' Q4 ' --+ CAST(@YEAR-1 AS VARCHAR)
END

ELSE 
BEGIN
SELECT @QUARTERNUMBER=CAST(substring (@QUARTER,2,1)AS INT)
SELECT @LOADINGQUARTER+' VS'+' Q' + CAST(@QUARTERNUMBER-1 AS VARCHAR)--	+' '+ CAST(@YEAR AS VARCHAR)
END

END