import { ISupply } from '../Interfaces/Dashboard/Report/DataTableAll/ISupply';
import { IConnectivity } from '../Interfaces/Dashboard/Report/MarketOverview/IConnectivity';

export const HighStrategicImpact = [
    "AWS to expand into Virginia’s Louisa County, develop two data center campuses northwest of Richmond",
    "Vantage plans for 1.7 million sq ft, three-building campus in Douglasville, in the Douglas County area of Atlanta, Georgia",
    "Google launches Berlin cloud region in Germany",
    "Google to spend $350m expanding Iowa data center",
    "Princeton Digital Group tops off 48MW data center in Tokyo, Japan, 100MW at full buildout by 2026",
    "PLDT eyes for 12th data center of 100MW at Greater Metro Manila",
    "Clark Delivers Latest NTT Data Center of 24MW (VA6) in Ashburn",
    "Fit-out complete at Colt DCS's 25MW Frankfurt data center",
    "Fit-out complete at Colt DCS's 25MW Frankfurt data center",
    "Principal acquires logistics site in Amsterdam, will be converted into 42MW data center for Switch DC",
    "KKR’s GTR to build 16MW data center in Barcelona, Spain"
]

export const MediumStrategicImpact = [
    "Equinix expands footprint in Mumbai(MB4) with an investment of $42 million",
    "Microsoft applies to build two data centers in San Jose, California",
    "Equinix expands footprint in Mumbai called MB4, with an investment of $42 million",
    "STT GDC Thailand announced \"STT Bangkok 3\", STT GDC's third data center in Thailand slated for opening by the end of 2023",
    "CyrusOne seeks planning permission for Dublin data center",
    "atNorth acquires HPC firm Gompute in Sweden"

]

export const SupplyData: ISupply[] = [
    { DataCenterId: 1, DataCenterName: "D1", DataCenterProvider: "Yotta Infrastructure Solutions", City: "Noida", Market: "New Delhi", Country: "India" },
    { DataCenterId: 2, DataCenterName: "HKG2", DataCenterProvider: "VantagevData Centers", City: "Fo Tan", Market: "Hong Kong", Country: "Hong Kong" },
    { DataCenterId: 3, DataCenterName: "D1", DataCenterProvider: "Yotta Infrastructure Solutions", City: "Noida", Market: "New Delhi", Country: "India" },
    { DataCenterId: 4, DataCenterName: "KDC SGP5", DataCenterProvider: "Keppel Data Center", City: "Singapore", Market: "Singapore", Country: "Singapore" },
    { DataCenterId: 5, City: "Noida", Country: "India", DataCenterName: "D1", Market: "New Delhi", DataCenterProvider: "Yotta Infrastructure Solutions" },
    
]

export const QoqValues = [{
    regionId: 1,
        TotalQoq: 49.01,
        TotalQoqpercentage: -3.39,
        AvailableQoq: -14.858,
        AvaialableQoqPercentage: 20.060,
        LessThanOneMWQoq: -33.08,
        LessThanOneMWQoqPercentage: 18.67,
        MoreThanOneMWQoq: 12.445,
        MoreThanOneMWQoqPercentage: 14.345
},
    {
        regionId: 2,
            TotalQoq: -27.34,
            TotalQoqpercentage: -2.59,
            AvailableQoq: 1.719,
            AvaialableQoqPercentage: 1.084,
            LessThanOneMWQoq: -13.08,
            LessThanOneMWQoqPercentage: 10.67,
            MoreThanOneMWQoq: 7.445,
            MoreThanOneMWQoqPercentage: 10.35
    },
    {
        regionId: 3,
            TotalQoq: 0.21,
            TotalQoqpercentage: 0.07,
            AvailableQoq: 1.662,
            AvaialableQoqPercentage: 3.98,
            LessThanOneMWQoq: 13.08,
            LessThanOneMWQoqPercentage: 10.67,
            MoreThanOneMWQoq: 2.445,
            MoreThanOneMWQoqPercentage: 7.345
    },
    {
        regionId: 4,
            TotalQoq: null,
            TotalQoqpercentage: null,
            AvailableQoq: null,
            AvaialableQoqPercentage: null,
            LessThanOneMWQoq: null,
            LessThanOneMWQoqPercentage: null,
            MoreThanOneMWQoq: null,
            MoreThanOneMWQoqPercentage: null
    },
]

export const ConnectivityData: IConnectivity[] =[ {
    GeographicalId: "GEO-10001938",
    ProviderId: "prov1",
    ProviderName: "Equinix, Inc.",
    RegionId: 1,
    Region: "Region 1",
    BusinessRegionId: 0,
    BusinessRegion: "Business Region 1",
    CountryId: 1,
    Country: "United States of America",
    StateId: 10,
    State: "State 1",
    CityId: 100,
    City: "Ashburn",
    Market: "Georgia Other",
    Internal: false,
    MarketId: "market1",
    Year: 2024,
    LocalAsn: 6614,
    Info_Type: "Cable/DSL/ISP",
    Latitude: "39.0437567",
    Longitude: "-77.4874416",
    FacilityName: "Equinix DC1-DC15, DC21 - Ashburn"
},
    {
        GeographicalId: "GEO-10002748",
        ProviderId: "prov1",
        ProviderName: "Digital Realty",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 1,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "United Kingdom",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "London",
        Market: "London",
        Internal: true,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 25577,
        Info_Type: "NSP",
        Latitude: "51.4944",
        Longitude: "-0.018595",
        FacilityName: "Equinix DC1-DC15, DC21 - Ashburn"
    },
    {
        GeographicalId: "GEO-10003542",
        ProviderId: "prov1",
        ProviderName: "Digital Realty",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 2,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "Austria",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Vienna",
        Market: "Vienna",
        Internal: true,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 25577,
        Info_Type: "NSP",
        Latitude: "48.210912596784034",
        Longitude: "16.378515874273528",
        FacilityName: "Digital Realty Vienna VIE1-2"
    },
    {
        GeographicalId: "GEO-10003460",
        ProviderId: "prov1",
        ProviderName: "Equinix, Inc.",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 3,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "Japan",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Tokyo",
        Market: "Tokyo",
        Internal: false,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 703,
        Info_Type: "NSP",
        Latitude: "35.688098983607453",
        Longitude: "139.71482667745494",
        FacilityName: "Equinix DC1-DC15, DC21 - Ashburn"
    },
    {
        GeographicalId: "GEO-10002900",
        ProviderId: "prov1",
        ProviderName: "MMTS-9 JSC",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 4,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "Russia",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Moscow",
        Market: "Moscow",
        Internal: true,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 207351,
        Info_Type: "NSP",
        Latitude: "55.676562",
        Longitude: "37.618974",
        FacilityName: "Moscow M9"
    }, {
        GeographicalId: "GEO-10002007",
        ProviderId: "Speedbone GmbH",
        ProviderName: "Provider 1",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 5,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "Germany",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Berlin",
        Market: "Berlin",
        Internal: true,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 62193,
        Info_Type: "NSP",
        Latitude: "52.47791651814314",
        Longitude: "13.305252856961486",
        FacilityName: "Moscow M9"
    }, {
        GeographicalId: "GEO-10002089",
        ProviderId: "prov1",
        ProviderName: "LCL Belgium",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 6,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "Belgium",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Brussels",
        Market: "Brussels",
        Internal: true,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 48638,
        Info_Type: "Enterprise",
        Latitude: "50.864181340347905",
        Longitude: "4.3530488787398047",
        FacilityName: "LCL Brussels (Diegem)"
    }, {
        GeographicalId: "GEO-10001906",
        ProviderId: "prov1",
        ProviderName: "Iron Mountain Data Centers",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 7,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "Netherlands",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Amsterdam",
        Market: "Amsterdam",
        Internal: false,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 39686,
        Info_Type: "NSP",
        Latitude: "52.3282",
        Longitude: "4.92586",
        FacilityName: "Iron Mountain Data Center - Amsterdam (AMS-1)"
    }, {
        GeographicalId: "GEO-10003269",
        ProviderId: "prov1",
        ProviderName: "Evocative, Inc.",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 8,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "United States of America",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Santa Clara",
        Market: "Silicon Valley",
        Internal: true,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 53292,
        Info_Type: null,
        Latitude: "37.376",
        Longitude: "-121.954",
        FacilityName: "Evocative SJC3"
    }, {
        GeographicalId: "GEO-10003333",
        ProviderId: "prov1",
        ProviderName: "Global Switch",
        RegionId: 1,
        Region: "Region 1",
        BusinessRegionId: 9,
        BusinessRegion: "Business Region 1",
        CountryId: 1,
        Country: "Singapore",
        StateId: 10,
        State: "State 1",
        CityId: 100,
        City: "Santa Clara",
        Market: "Singapore",
        Internal: true,
        MarketId: "market1",
        Year: 2024,
        LocalAsn: 38193,
        Info_Type: "NSP",
        Latitude: "1.328",
        Longitude: "103.746",
        FacilityName: "Global Switch Singapore"
    }
]
