CREATE TABLE [dbo].[Opportunity] (
    [ID]                   INT             IDENTITY (1, 1) NOT NULL,
    [Market]               VARCHAR (255)   NULL,
    [Stag]                 VARCHAR (255)   NULL,
    [Probability]          FLOAT (53)      NULL,
    [QuarterID]            INT             NULL,
    [OpportunityName]      VARCHAR (255)   NULL,
    [Property]             NVARCHAR (255)  NULL,
    [Industry]             VARCHAR (255)   NULL,
    [ProductType]          VARCHAR (255)   NULL,
    [TotalkW]              FLOAT (53)      NULL,
    [RaisedSqFt]           FLOAT (53)      NULL,
    [RentableSf]           FLOAT (53)      NULL,
    [AnnualizedGAAPRent]   FLOAT (53)      NULL,
    [TransactionType]      VARCHAR (255)   NULL,
    [OpportunityOwner]     VARCHAR (255)   NULL,
    [DateCreated]          DATE            CONSTRAINT [DF_Demand_DateCreated] DEFAULT (getdate()) NULL,
    [DateModified]         DATETIME        NULL,
    [ModifiedBy]           VARCHAR (255)   NULL,
    [IsActive]             BIT             CONSTRAINT [DF_Demand_IsActive] DEFAULT ((1)) NULL,
    [Region]               VARCHAR (255)   NULL,
    [IsUpdated]            BIT             NULL,
    [IsNew]                BIT             NULL,
    [RC First Month Rent]  NUMERIC (18, 2) NULL,
    [Supply/Demand Rating] NVARCHAR (40)   NULL,
    [Starting $/kW]        NUMERIC (18, 2) NULL,
    [AverageRent]          FLOAT (53)      NULL,
    [Average $/kW]         NUMERIC (18, 2) NULL,
    [IsDeleted]            BIT             NULL,
    CONSTRAINT [PK_Demand] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80)
);

