CREATE TABLE [dbo].[TempImportDLRInventory] (
    [Region]                             NVARCHAR (255) NULL,
    [Market]                             NVARCHAR (255) NULL,
    [QuarterID]                          INT            NULL,
    [Name]                               NVARCHAR (255) NULL,
    [TotalRentableSqft]                  FLOAT (53)     NULL,
    [KWofUPS]                            FLOAT (53)     NULL,
    [SuiteCondition]                     NVARCHAR (255) NULL,
    [PropertyCode]                       NVARCHAR (255) NULL,
    [Property]                           NVARCHAR (255) NULL,
    [DateModified]                       DATETIME       NULL,
    [ModifiedBy]                         NVARCHAR (255) NULL,
    [ProductType]                        NVARCHAR (255) NULL,
    [GlobalRegion]                       NVARCHAR (200) NULL,
    [EarliestDeliveryDate]               DATETIME       NULL,
    [SignedOrPendingLease]               INT            NULL,
    [TotalROFO]                          FLOAT (53)     NULL,
    [ROFOCustomer]                       NVARCHAR (MAX) NULL,
    [TotalActive3rdPartyInterest]        FLOAT (53)     NULL,
    [Prospect]                           NVARCHAR (MAX) NULL,
    [Comments]                           NVARCHAR (MAX) NULL,
    [TotalPlannedITLoad]                 FLOAT (53)     NULL,
    [StrategicInitiative]                BIT            NULL,
    [MoveInReadyInitiative]              BIT            NULL,
    [CompanyName]                        VARCHAR (255)  NULL,
    [AirportCode]                        VARCHAR (255)  NULL,
    [AssetScoring]                       VARCHAR (255)  NULL,
    [ProjectScope]                       VARCHAR (MAX)  NULL,
    [DeliveryStatus]                     VARCHAR (255)  NULL,
    [ResponsibleParty]                   VARCHAR (255)  NULL,
    [WaterCooling]                       VARCHAR (100)  NULL,
    [TargetProductSize]                  NVARCHAR (100) NULL,
    [SecurePerimeter]                    VARCHAR (255)  NULL,
    [IndustryOrComplianceCertifications] VARCHAR (255)  NULL,
    [CloudOnRamp]                        VARCHAR (255)  NULL,
    [NetworkDensity]                     VARCHAR (255)  NULL,
    [SmartHands]                         VARCHAR (255)  NULL,
    [EstimatedCostsUSD]                  FLOAT (53)     NULL,
    [PowerDensity]                       FLOAT (53)     NULL,
    [LargestContiguousSuite]             FLOAT (53)     NULL,
    [CPS]                                NVARCHAR (100) NULL
);

