namespace Easify.Contracts.Common
{
    /// <summary>
    /// Interface IConfigurationProvider
    /// </summary>
    public interface IConfigurationProvider
    {
        public string Host { get; set; }
        public int Port { get; set; }
        public string TestMailNote { get; set; }
        public string AutoGeneratedNote { get; set; }

        public string UserName { get; set; }
        public string Password { get; set; }
        public string SiteUrl { get; set; }
        public string TenantUrl { get; set; }
        public string EmailSender { get; set; }
        public string AppUrl { get; set; }
        public string DocumentLibrary { get; set; }
        public string AnalysisDocumentLibrary { get; set; }
        public string BattlecardsDocumentLibrary { get; set; }
        public string CapacityDocumentLibrary { get; set; }
        public string SecretShopperDocumentLibrary { get; set; }
        public string SupportTeam { get; set; }
        public string DLREmail { get; set; }
    }
}
