using Easify.Concerns.Common;
using Microsoft.Extensions.Configuration;
using System;

namespace Easify.Providers.Common
{
    /// <summary>
    /// Class ConfigurationProvider.
    /// Implements the <see cref="Easify.Contracts.Common.IConfigurationProvider" />
    /// </summary>
    /// <seealso cref="Easify.Contracts.Common.IConfigurationProvider" />
    public class ConfigurationProvider : Contracts.Common.IConfigurationProvider
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationProvider"/> class.
        /// </summary>
        /// <param name="configuration">The configuration.</param>
        public ConfigurationProvider(IConfiguration configuration)
        {
            this.Host = configuration[Constants.Host];
            this.Port = Convert.ToInt32(configuration[Constants.Port]);
            this.TestMailNote = configuration[Constants.TestMailNote];
            this.AutoGeneratedNote = configuration[Constants.AutoGeneratedNote];
            this.UserName = configuration[Constants.UserName];
            this.Password = configuration[Constants.Password];
            this.SiteUrl = configuration[Constants.SiteUrl];
            this.EmailSender = configuration[Constants.EmailSender];
            this.AppUrl = configuration[Constants.AppUrl];
            this.DocumentLibrary = configuration[Constants.DocumentLibrary];
            this.AnalysisDocumentLibrary = configuration[Constants.AnalysisDocumentLibrary];
            this.BattlecardsDocumentLibrary = configuration[Constants.BattlecardsDocumentLibrary];
            this.CapacityDocumentLibrary = configuration[Constants.CapacityDocumentLibrary];
            this.SecretShopperDocumentLibrary= configuration[Constants.SecretShopperDocumentLibrary];
            this.SupportTeam= configuration[Constants.SupportTeam];
            this.DLREmail= configuration[Constants.DLREmail];
        }

        public string Host { get; set; }
        public int Port { get; set; }
        public string TestMailNote { get; set; }
        public string AutoGeneratedNote { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SiteUrl { get; set; }
        public string TenantUrl { get; set; }
        public string EmailSender { get; set; }
        public string AppUrl { get; set; }
        public string DocumentLibrary { get; set; }
        public string AnalysisDocumentLibrary { get; set;}
        public string BattlecardsDocumentLibrary { get;set; }
        public string CapacityDocumentLibrary { get; set; }
        public string SecretShopperDocumentLibrary { get; set; }
        public string SupportTeam { get; set; }
        public string DLREmail { get; set; }
    }
}
