

CREATE VIEW [dbo].[Supply_Cube_TestSwet] AS 
SELECT [ID]
	  ,'Region' = CASE WHEN ([Region] = '' OR [Region] IS NULL) THEN 'Not Assigned' ELSE rtrim(ltrim([Region])) END
	  ,'Market' = CASE WHEN ([Market] = '' OR [Market] IS NULL) THEN 'Not Assigned' ELSE rtrim(ltrim([Market])) END
      ,[QuarterID] AS [QuarterID]
      ,rtrim(ltrim([Name])) AS [Name]
      ,[TotalRentableSqft]  AS [TotalRentableSqft]
      ,[TotalRaisedFloorSqft] AS [TotalRaisedFloorSqft]
      ,[kWofUPS] AS [kWofUPS]
      ,rtrim(ltrim([SuiteCondition])) AS [SuiteCondition]
      ,rtrim(ltrim([Status])) AS [Status]
      ,[DateAvailable] AS [DateAvailable]
      ,rtrim(ltrim([InventoryType])) AS [InventoryType]
      ,rtrim(ltrim([PropertyCode])) AS [PropertyCode]
      ,rtrim(ltrim([Property])) AS [Property]
      ,[DateModified] AS [DateModified]
      ,rtrim(ltrim([ModifiedBy])) AS [ModifiedBy]
      ,[DateCreated] AS [DateCreated]
      ,[IsActive] AS [IsActive]
      ,[IsNew] AS [IsNew]
      ,rtrim(ltrim([ProductType])) AS [ProductType]
	  ,'GlobalRegion' = CASE WHEN ([GlobalRegion] = '' OR [GlobalRegion] IS NULL) THEN 'Not Assigned' ELSE rtrim(ltrim([GlobalRegion])) END
      ,[EarliestDeliveryDate] AS [EarliestDeliveryDate]
      ,[TotalSigned/Pending] AS [TotalSigned/Pending]
      ,[TotalROFO(kW)] AS [TotalROFO(kW)]
	  ,'ROFOCustomer' = CASE WHEN ([ROFOCustomer] = '' OR [ROFOCustomer] IS NULL) THEN 'Not Assigned' ELSE rtrim(ltrim([ROFOCustomer])) END
      ,[TotalActive3rdPartyInterest(kW)] AS [TotalActive3rdPartyInterest(kW)]
      ,rtrim(ltrim([Prospect(s)])) AS [Prospect(s)]
      ,rtrim(ltrim([Comments])) AS [Comments]
	  ,rtrim(ltrim([CompanyName])) AS [CompanyName]
	  ,rtrim(ltrim([AirportCode])) AS [AirportCode]
	  ,rtrim(ltrim([AssetScoring])) AS [AssetScoring]
	  ,rtrim(ltrim([ProjectScope])) AS [ProjectScope]
	  ,rtrim(ltrim([DeliveryStatus])) AS [DeliveryStatus]
	  ,rtrim(ltrim([ResponsibleParty])) AS [ResponsibleParty]
	  ,rtrim(ltrim([WaterCooling])) AS [WaterCooling]
	  ,rtrim(ltrim([SmartHands])) AS [SmartHands]
	  ,rtrim(ltrim([NetworkDensity])) AS [NetworkDensity]
	  ,rtrim(ltrim([CloudOnRamp])) AS [CloudOnRamp]
	  ,rtrim(ltrim([IndustryOrComplianceCertifications])) AS [IndustryOrComplianceCertifications]
	  ,rtrim(ltrim([SecurePerimeter])) AS [SecurePerimeter]
	  ,[EstimatedCostsUSD] AS [EstimatedCostsUSD]
	  ,[PowerDensity] AS [PowerDensity]
  FROM [dbo].[DLRInventory]